apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs
  namespace: dogs
  labels:
    app: dogs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
        - name: dogs
          # Replace <GITHUB_OWNER> with your GitHub org/user if needed
          image: ghcr.io/bcxpsebastian/dogs:01a834e5d34ed7a314dc4dbc8cab89946c9f2b16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
