apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dogs-ingress
  namespace: dogs
  annotations:
    # Add ingress controller specific annotations as needed
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dogs
                port:
                  number: 80
